### ISSUE TITLE
Cannot show event

### ISSUE THREAD

**Issue by laney** [djcas9/legacy-snorby#14]
Hello all,
I've got it working well enough to display snort events in Dashboard and Events, but when I tried to drill down into any event I got error:
ActionView::TemplateError (undefined method `interface' for nil:NilClass) on line #16 of app/views/events/_summary.html.e
rb:
13:                     </tr>
14:                     <tr>
15:                             <td><%= @event.sensor.id %></td>
16:                             <td><%= @event.sensor.interface %></td>
17:                             <td><%= @event.sensor.hostname %></td>
18:                             <%- if @event.sig.sig_gid == 1 -%>
19:                             <td><%= link_to "#{@event.sig.sig_gid}:#{@event.sig.sig_sid}", "http://rootedyour.com/sno
rtsid?sid=#{@event.sig.sig_sid}", :target => '_blank', :title => 'More Information', :class => 'add_tipsy' %></td>

```
app/views/events/_summary.html.erb:16
app/views/events/show.html.erb:27
app/controllers/events_controller.rb:16:in `show'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering template within layouts/application
Rendering /errors/500.html.erb (500 Internal Server Error)

**Comment by laney** [comment]
OK. I just reset/setup/update, and it works.
I got my detailed event view back, but found another issue with PDF ... new thread then ;)
