### ISSUE TITLE
gem_original_require no such file to load prawn/format MissingSourceFile

### ISSUE THREAD

**Issue by garlandkr** [djcas9/legacy-snorby#34]
while running this:

/var/www/Snorby/script/runner -e production "Event.run_daily_report" >> /var/www/Snorby/log/snorby_reports.log

I get this:

/usr/local/lib/ruby/gems/1.8/gems/rails-2.3.2/lib/rails/gem_dependency.rb:99:Warning: Gem::Dependency#version_requirements is deprecated and will be removed on or after August 2010.  Use #requirement
/usr/local/lib/ruby/gems/1.8/gems/rails-2.3.2/lib/commands/runner.rb:48: /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- prawn/format (MissingSourceFile)
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/dependencies.rb:158:in `require'
        from /var/www/Snorby/lib/pdf_for_email.rb:3
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`gem_original_require'
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/dependencies.rb:158:in`require'
        from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/dependencies.rb:265:in `require_or_load'
        from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/dependencies.rb:425:in`load_missing_constant'
        from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/dependencies.rb:80:in `const_missing'
        from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/dependencies.rb:92:in`const_missing'
        from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/dependencies.rb:437:in `load_missing_constant'
        from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/dependencies.rb:96:in`const_missing'
        from /var/www/Snorby/app/models/event.rb:54:in `run_daily_report'
        from (eval):1
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`eval'
        from /usr/local/lib/ruby/gems/1.8/gems/rails-2.3.2/lib/commands/runner.rb:48
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /var/www/Snorby/script/runner:3

**Comment by garlandkr** [comment]
this is a copy of 28 that I didn't find in my search.
