### ISSUE TITLE
Dashboard rendering produces "Mysql::Error: MySQL server has gone away"

### ISSUE THREAD

**Issue by rhelfter** [djcas9/legacy-snorby#35]
Rendering pages/dashboard

ActionView::TemplateError (Mysql::Error: MySQL server has gone away: SELECT count(*) AS count_all FROM `users` WHERE (last_request_at > '2010-07-20 19:23:23') ) on line #3 of app/views/layouts/_footer.html.erb:
1: <div id='c_footer'>
2:      <div id="footer_text">
3:              &copy; 2010 <%= link_to "IPsecure 1.0.0 (build 56)", "http://www.ipsoft.com", :target => '_blank', :title => "http://www.ipsoft.com", :id => 'snorby_footer_info' %> - <%= pluralize User.logged_in.count, "user" %> currently logged in
4:      </div>
5: </div>

```
app/views/layouts/_footer.html.erb:3
app/views/layouts/application.html.erb:45
<internal:prelude>:8:in `synchronize'
/apps/IPsoft/ruby191/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
/apps/IPsoft/ruby191/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
/apps/IPsoft/ruby191/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
```

Rendering template within layouts/application
Rendering /errors/500.html.erb (500 Internal Server Error)
# gem list

**\* LOCAL GEMS ***

actionmailer (2.3.8, 2.3.2)
actionpack (2.3.8, 2.3.2)
activerecord (2.3.8, 2.3.2)
activeresource (2.3.8, 2.3.2)
activesupport (2.3.8, 2.3.2)
Ascii85 (1.0.0)
chronic (0.2.3)
color (1.4.1)
hoe (2.6.1)
json_pure (1.4.3)
mysql (2.8.1)
pdf-reader (0.8.5)
pdf-writer (1.1.8)
prawn (0.8.4, 0.6.2)
prawn-core (0.8.4, 0.6.3, 0.6.2)
prawn-format (0.2.3)
prawn-layout (0.8.4, 0.3.2)
prawn-security (0.8.4, 0.1.1)
rack (1.2.1, 1.1.0)
rails (2.3.8, 2.3.2)
rake (0.8.7)
rubyforge (2.0.4)
transaction-simple (1.4.0)
whenever (0.5.0)

Post login, post redirection to /dashboard, if I go to /events, the pages render.
# ruby -v

ruby 1.9.1p378 (2010-01-10 revision 26273) [i686-linux]

]# gem -v
1.3.5

**Comment by rhelfter** [comment]
Nevermind, reinstalling fixed the problem

**Comment by rhelfter** [comment]
closing
