### ISSUE TITLE
undefined method `interface' for nil:NilClass

### ISSUE THREAD

**Issue by onelson** [djcas9/legacy-snorby#37]
Hi, I'm getting the following trace from the event drill down page:

```
Processing EventsController#show (for 10.0.0.1 at 2010-08-26 14:47:22) [GET]
Parameters: {"action"=>"show", "id"=>"1,17819", "controller"=>"events"}
Rendering template within layouts/application
Rendering events/show

ActionView::TemplateError (undefined method `interface' for nil:NilClass) on line #16 of app/views/events/_summary.html.erb:
13:                     </tr>
14:                     <tr>
15:                             <td><%= @event.sensor.id %></td>
16:                             <td><%= @event.sensor.interface %></td>
17:                             <td><%= @event.sensor.hostname %></td>
18:                             <%- if @event.sig.sig_gid == 1 -%>
19:                             <td><%= link_to "#{@event.sig.sig_gid}:#{@event.sig.sig_sid}", "http://rootedyour.com/snortsid?sid=#{@event.sig.sig_sid}", :target => '_blank', :title => 'More Information', :class => 'add_tipsy' %></td>

    app/views/events/_summary.html.erb:16
    app/views/events/show.html.erb:27
    app/controllers/events_controller.rb:16:in `show'
    thin (1.2.5) lib/thin/connection.rb:76:in `pre_process'
    thin (1.2.5) lib/thin/connection.rb:74:in `catch'
    thin (1.2.5) lib/thin/connection.rb:74:in `pre_process'
    thin (1.2.5) lib/thin/connection.rb:57:in `process'
    thin (1.2.5) lib/thin/connection.rb:42:in `receive_data'
    eventmachine (0.12.10) lib/eventmachine.rb:256:in `run_machine'
    eventmachine (0.12.10) lib/eventmachine.rb:256:in `run'
    thin (1.2.5) lib/thin/backends/base.rb:57:in `start'
    thin (1.2.5) lib/thin/server.rb:156:in `start'
    thin (1.2.5) lib/thin/controllers/controller.rb:80:in `start'
    thin (1.2.5) lib/thin/runner.rb:177:in `send'
    thin (1.2.5) lib/thin/runner.rb:177:in `run_command'
    thin (1.2.5) lib/thin/runner.rb:143:in `run!'
    thin (1.2.5) bin/thin:6
    /usr/bin/thin:19:in `load'
    /usr/bin/thin:19

Rendering template within layouts/application
Rendering /errors/500.html.erb (500 Internal Server Error)
```

I tried running both stable and master, but got the same thing.  Any ideas?

**Comment by kesterb** [comment]
I was getting the same error.  On a whim I tried:
rake snorby:reset RAILS_ENV=production   # ALL DATA WILL BE LOST

My issue was fixed, but as promised all of my alerts were lost.  No biggie since this was a new install.

**Comment by onelson** [comment]
Yeah, I'm not sure what that was about.  The issue just disappeared (over night).  I'd say the cron must have populated the missing properties that the view was expecting, but when I setup the app, the cron jobs didn't install... so... yeah.  Seemed like maybe it was because I hit refresh on the dashboard -- can't say for sure.
